name: Deploy

on:
  push:
    branchs: ["master"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install .NET Wasm Tools
        run: dotnet workload install wasm-tools

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Publish .NET
        run: dotnet publish TachittesApp -c:Release -o docs --nologo

      - name: Adjust Base Path
        run: |
          OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          echo "Nome do proprietário: $OWNER"
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          echo "Nome do repositório: $REPO_NAME"
          FULL_PATH="${OWNER}.github.io/${REPO_NAME}"
          echo "Caminho base completo: /$FULL_PATH/"
          sed -i "s|<base href=\"/\" />|<base href=\"/${FULL_PATH}/\" />|g" docs/wwwroot/index.html
          sed -i "s|const base = \"/\"|const base = \"/${FULL_PATH}/\"|g" docs/wwwroot/service-worker.js

      - name: Add .nojekyll file
        run: touch docs/wwwroot/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/wwwroot'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
